#!/bin/zsh

## Description: Copy the installation profile over to the test instance, rebuild and launch the instance
## Usage: pb-dev-test-profile

## README
# This command simplifies the process of testing the install profile
# It does several things on the test instance:
# — Copies the profile code to the test instance
# - Executes composer install
# - Reinstalls the site

# Find the path to the test instance
DEV_INSTANCE_PATH=${DDEV_APPROOT}
PATH_COMPONENTS=(${(s[/])DEV_INSTANCE_PATH})
CURRENT_DIR_NAME=$PATH_COMPONENTS[-1]
TEST_INSTANCE_PATH=${DEV_INSTANCE_PATH/$CURRENT_DIR_NAME/prussianblue-test}

# Copy the profile code to the root of the test instance, to let
# it be installed by Composer as a local repository, see
# https://medium.com/pvtl/local-composer-package-development-47ac5c0e5bb4
DEV_PROFILE_PATH="${DDEV_APPROOT}/web/profiles/contrib/prussianblue"
TEST_PROFILE_PATH="${TEST_INSTANCE_PATH}/prussianblue-profile"
rm -rf $TEST_PROFILE_PATH
cp -r $DEV_PROFILE_PATH $TEST_PROFILE_PATH

# TODO: MAKE THE SITE INSTALL ACTUALLY HAPPEN
cd $TEST_INSTANCE_PATH
ddev composer update prussianblue-cms/prussianblue --prefer-source
ddev drush sin prussianblue -y
ddev drush cr
ddev drush uli | pbcopy