#!/bin/bash

ddev drush site-install --site-name=${DDEV_PROJECT} --account-name=admin --account-mail=web-admin@matrushka.com.mx --site-mail=web-admin@matrushka.com.mx --yes
ddev drush en --yes layout_paragraphs layout_paragraphs_permissions layout_section_classes link_attributes metatag passwordless publishcontent responsive_favicons responsive_preview smtp url_embed
