#!/bin/bash

ddev drush site-install --site-name=${DDEV_PROJECT} --account-name=admin --account-mail=web-admin@matrushka.com.mx --site-mail=web-admin@matrushka.com.mx --yes

# Contrib and Core modules
ddev drush en --yes layout_paragraphs layout_paragraphs_permissions layout_section_classes link_attributes metatag passwordless publishcontent responsive_favicons smtp url_embed twig_tweak media media_library admin_toolbar locale content_translation config_translation

# Contrib modules we maintain, or PB-specific modules
ddev drush en --yes freeform

# Enable and then uninstall builder modules
ddev drush en --yes pb_base_paragraphs pb_content_type_page
ddev drush pmu --yes pb_base_paragraphs pb_content_type_page

# Enable the runtime modules
ddev drush en --yes pb_layouts pb_editor_ui

# Enable the paragraphs connector and content type modules,
# run the connector command and disable the modules
ddev drush en --yes pb_paragraphs_connector pb_content_type_page
ddev pb-paragraphs-connect
ddev drush pmu --yes pb_paragraphs_connector pb_content_type_page

# Enable the pb admin theme
ddev drush thin --yes pb_admin_theme
ddev drush cset --yes system.theme admin pb_admin_theme
